### ISSUE TITLE
colour / color

### ISSUE THREAD

**Issue by team-tech-works-uk** [patrickknabe/node-red-contrib-ui-digital-display#2]
great widget - wld love to use - but need different colours (mainly brighter) .. any advice ? many thanks

**Comment by patrickknabe** [comment]
Hello,

thank you very much for your feedback. At the moment, the colors of the dashboard theme are used to colorize the widget. However, I plan to create a 2nd version where it will also be possible to display letters. In doing so, I might also think about a custom color choice.

Many greetings

Patrick

**Comment by Gun-neR** [comment]
A workaround is to add a template node with the following

`<style >
.nr-dashboard-ui_digital_display.visible svg path {
--nr-dashboard-pageTitlebarBackgroundColor : red;
}
</style>`

As per this topic... https://discourse.nodered.org/t/changing-the-base-color-setting-via-css/51497
