### ISSUE TITLE
Display does not appear in Safari - until you use developer tools

### ISSUE THREAD

**Issue by juggledad** [patrickknabe/node-red-contrib-ui-digital-display#3]
Node-RED version: v1.3.3
Node.js  version: v12.22.1
node-red-dashboard: v2.29.1
node-red-contrib-ui-digital-display: v1.0.1

device: Raspberry Pi 3 Model B Rev 1.2
browsers running on macOS Mojave v10.14.6

When I open the dashboard using Safari, the digital display does not appear however as soon as I open the 'Show Web Inspector' or any of the developer tools, the digital display appears. 

If I use FrieFox or Chrome, the display appears as soon as the page opens.

Let me know what other information you might need.

**Comment by patrickknabe** [comment]
Hello,

I will try to get hold of an OSX test system in the coming week to check the behavior. At the moment I have no idea what the reason is that the display is not shown immediately.

Many greetings

Patrick

**Comment by dodois** [comment]
The same problem appears on my iPad on top of Chrome

**Comment by patrickknabe** [comment]
Hello all,

I have been able to track and fix the Safari browser display error. Please test the behavior once. I would be very happy about a feedback!

Many greetings

Patrick

**Comment by dodois** [comment]
@patrickknabe Looks good after I tested it

**Comment by dodois** [comment]
@patrickknabe Can you describe the problem, I feel strange, is it related to SVG?

**Comment by patrickknabe** [comment]
Safari has a different behaviour when scaling SVG images. In Chrome you just need to set the height and the width ist calculated by the viewbox automatically. Safari only sets the height and makes the width 0px. Setting height to -webkit-fit-content solves this... for all browsers.

**Comment by dodois** [comment]
@patrickknabe On Windows Chrome. The ui-digital, which is not assigned in time, will show 8888888 and I have to refresh the page manually.

**Comment by patrickknabe** [comment]
@dodois Can you give me an example flow, which shows the problem?!

**Comment by dodois** [comment]
![image](https://user-images.githubusercontent.com/73285310/125050176-52192400-e0d4-11eb-87aa-c64f28bec6e4.png)

**Comment by patrickknabe** [comment]
Fixed now!
