### ISSUE TITLE
Value lost when changing groups

### ISSUE THREAD

**Issue by linuxtrap** [patrickknabe/node-red-contrib-ui-digital-display#4]
Just like to report that value not showing if you change to an other dashboard group and back again, 
the value come back after a page reload. 

Hope its something you can look in to 

PT

**Comment by patrickknabe** [comment]
Hi,

I just corrected the behaviour when changing tabs on the dashboard and released a new version of the display (v1.0.3). Should be already available.

Maybe you can give me a short feedback?

Have fun with it and best regards
Patrick

**Comment by linuxtrap** [comment]
Did run the update, and all works good now.

Thanks for the update, I use it to display the hourly price of electricity up on a screen.

PT

**Comment by patrickknabe** [comment]
I'm glad to hear it! May I possibly make the request for a screenshot? Of course, only if no confidential information is revealed in the process. I would like to have more feedback about the applications in which the display is used, in order to get impulses for further development. But please really only if it's okay with you!

Best regards
Patrick

**Comment by linuxtrap** [comment]
Its used to show the price on electricity, now, and hour next and before 
[
![image](https://user-images.githubusercontent.com/841756/145827868-53db84e7-c3ab-4cea-9e03-85f4ee8baa79.png)
](url)

**Comment by patrickknabe** [comment]
Thank you so much!

**Comment by linuxtrap** [comment]
One more thing, If you change to Angular Theme it look like this:
![image](https://user-images.githubusercontent.com/841756/146507078-65bf9bf1-61fb-4e82-bd05-8fb5cda092b9.png)
Not a good color combination..... Its nothing im using, but some might :)

PT

**Comment by patrickknabe** [comment]
I had a lot of questions for individual colors. I think during the next months I will add settings for color adjustment.
